### ISSUE TITLE
I want carol to run in the browser!

### ISSUE THREAD

**Issue by elinahedenius** [elinahedenius/elinahedenius.github.io#1]
I want carol to run in the browser when i click the 'go back' button in depression.html, preferably on a new page that is linked in the button. I have no idea how to do this what so ever.

**Comment by ahstro** [comment]
Hmm, unfortunately you can't run Python in the browser. Only programming language that runs in web browsers is JavaScript, which is why it's so popular. So you probably want to rewrite it in JS :/

**Comment by elinahedenius** [comment]
:( that sux
do i have to learn javascript or is there some fancy converter somewhere? (also thank u!)

**Comment by ahstro** [comment]
Might be some converter somewhere, but it would probably require some tweaking. Learning JavaScript is a pretty darn valuable skill though ;)

**Comment by elinahedenius** [comment]
I'm officially on it!
