### ISSUE TITLE
I don't undersand domains.

### ISSUE THREAD

**Issue by elinahedenius** [elinahedenius/elinahedenius.github.io#2]
boswebsite.art is currently redirecting to elinahedenius.github.io and I want it to be the other way around :( 
How do I fix this?

**Comment by JohnTendik** [comment]
Follow this guide:

https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a

**Comment by elinahedenius** [comment]
Thank you!!
